### ISSUE TITLE
Error in the PlayerToggleSneakEvent

### ISSUE THREAD

**Issue by DarkSavci** [ItzAmirreza/EzChestShop#46]
The plugin gives an error when you sneak while looking to a regular (non-shop) chest.
I think adding following code after the 241. line on the ```PlayerCloseToChestListener.java``` will fix the issue but I can't test.
```if (!ShopContainer.isShop(loc)) return;```

Console log of the error:
```
- [Mon 18:05:44 ERROR Minecraft] Could not pass event PlayerToggleSneakEvent to EzChestShop v1.5.4
java.lang.NullPointerException: Cannot invoke "String.getBytes(java.nio.charset.Charset)" because "src" is null
    at java.base/java.util.Base64$Decoder.decode(Base64.java:589)
    at EzChestShop-1.5.4.jar//me.deadlight.ezchestshop.Utils.Utils.decodeItem(Utils.java:118)
    at EzChestShop-1.5.4.jar//me.deadlight.ezchestshop.Listeners.PlayerCloseToChestListener.onPlayerSneak(PlayerCloseToChestListener.java:279)
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor671.execute(Unknown Source)
    at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
    at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
    at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
    at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerCommand(ServerGamePacketListenerImpl.java:2621)
    at net.minecraft.network.protocol.game.ServerboundPlayerCommandPacket.handle(ServerboundPlayerCommandPacket.java:37)
    at net.minecraft.network.protocol.game.ServerboundPlayerCommandPacket.handle(ServerboundPlayerCommandPacket.java:13)
    at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51)
    at net.minecraft.server.TickTask.run(TickTask.java:18)
    at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153)
    at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
    at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341)
    at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:
```

**Comment by ElitoGame** [comment]
Thanks for pointing this out, I added the line and tested it with various containers - Chest, Doublechest. trapped Chest, Shulker, barrel. Seems to work fine now! Next ECS release will contain the fix =)
