### ISSUE TITLE
created chest shop error

### ISSUE THREAD

**Issue by xiaocheng168** [ItzAmirreza/EzChestShop#68]
java.lang.NullPointerException: Cannot invoke "me.deadlight.ezchestshop.utils.ImprovedOfflinePlayer.fromOfflinePlayer(org.bukkit.OfflinePlayer)" because "me.deadlight.ezchestshop.utils.ImprovedOfflinePlayer.improvedOfflinePlayer" is null
        at me.deadlight.ezchestshop.utils.XPEconomy.getXP(XPEconomy.java:9) ~[EzChestShop-1.6.5 (1).jar:?]
        at me.deadlight.ezchestshop.utils.Utils.calculateBuyPossibleAmount(Utils.java:587) ~[EzChestShop-1.6.5 (1).jar:?]
        at me.deadlight.ezchestshop.utils.Utils.calculatePossibleAmount(Utils.java:572) ~[EzChestShop-1.6.5 (1).jar:?]
        at me.deadlight.ezchestshop.guis.AdminShopGUI.showGUI(AdminShopGUI.java:200) ~[EzChestShop-1.6.5 (1).jar:?]
        at me.deadlight.ezchestshop.listeners.ChestOpeningListener.onChestOpening(ChestOpeningListener.java:132) ~[EzChestShop-1.6.5 (1).jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor36.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:git-Purpur-2095]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:595) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:538) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1978) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:53) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1351) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1328) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1321) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1299) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1187) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

PLUGIN
    > version EzChestShop
    [01:03:45 INFO]: EzChestShop version 1.6.5
    [01:03:45 INFO]: Easy Chest Shop that any server owner wants that for his/her players
    [01:03:45 INFO]: Authors: ItzAmirreza and ElitoGame
SERVER
    Current: git-Purpur-2095 (MC: 1.20.2)

this is bug?

**Comment by ItzAmirreza** [comment]
Minecraft version 1.20.2 is not supported while you are using ECS 1.6.5. Either upgrade your server to 1.20.4, or downgrade the plugin version to 1.6.4.6
